ALTER TABLE Student DROP COLUMN ATER

ALTER TABLE Student 
ALTER COLUMN Age FLOAT

ALTER TABLE Student 
ADD Enroll DATE

ALTER TABLE STUDENT
ADD GENDER BIT


INSERT Student(id,[Name])VALUEs(4,N'李开发');
INSERT STUDENT VALUES(5,N'邵浩浩',null,null,null,null);

SELECT * FROM STUDENT
SELECT AGE,id FrOM Student

update student set age=18