CREATE TABLE[dbo].Student
(
[ID]INT NOT NULL PRIMARY  KEY,
[Name]NCHAR(10)NULL,
[Age]nchar(10)null,
)
ALTER TABLE Student
ADD ATER DECIMAL(3,1);
ALTER TABLE Student
ALTER COLUMN SCORE FLOAT NULL;
ALTER TABLE Student
ALTER COLUMN ATER DECIMAL(3,2);

DROP TABLE dbo.[TABLE]