ALTER TABLE Student DROP COLUMN ATER

ALTER TABLE Student 
ALTER COLUMN Age FLOAT

ALTER TABLE Student 
ADD Enroll DATE

ALTER TABLE STUDENT
ADD GENDER BIT


INSERT Student(id,[Name])VALUEs(4,N'李开发');
INSERT STUDENT VALUES(5,N'邵浩浩',null,null,null,null);

SELECT * FROM STUDENT
SELECT AGE,id FrOM Student

select * from student
ALTER TABLE STUDENT 
ALTER COLUMN FONT NCHAR(10)

INSERT STUDENT (ID,[name]) values (7,N'陈教主');

SELECT ID,[NAME] FROM STUDENT;

UPDATE STUDENT SET SCORE=2000

DELETE STUDENT

WHERE ID BETWEEN 3 AND 5